
# jdbc连接配置
spring:
  datasource:
    url: jdbc:sqlite:{classpath}:/dbfile/spboot.db
    driver-class-name: org.sqlite.JDBC
    data-username:
    data-password:
    schema: {classpath}:classpath:/dbfile/import.sql

mybatis:
  config-location: {classpath}:/mybatis/mybatis.config




